name: Daily WhatsApp Message

on:
  schedule:
    - cron: '30 3 * * *'  # Runs at 9 AM IST = 3:30 AM UTC
  workflow_dispatch:       # Allows manual runs

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run WhatsApp Script
      run: python main.py
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_ACCOUNT_AUTH: ${{ secrets.TWILIO_ACCOUNT_AUTH }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
