name: Send Daily Vocab

on:
  schedule:
    - cron: '30 3 * * *' # 9 AM IST (3:30 AM UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_ACCOUNT_AUTH: ${{ secrets.TWILIO_ACCOUNT_AUTH }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_BOT: ${{ secrets.TELEGRAM_BOT }}
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
